### ISSUE TITLE
Update Jest Testing

### ISSUE THREAD

**Issue by finnnilsen90** [finnnilsen90/finn_website#2]
Currently Jest tests are not set up to test many different UI features and Javascript logic. On top of this it is very difficult to test components individually. 

**Todo**

- [ ] Set up gulp to create specifically named test files according to the component being tested. Follow below syntax.
compName.test.js

- [ ] Better set up structure to test UI.

- [ ] Better test Javascript logic
